<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="AFS Doubt, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] AFS Doubt AFS/DDC/OLE: Function servers" />
	
	<title>AFS Doubt [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="index.html">Newbaanboard</a> &gt; <a href="index.html">Baan SIGs</a> &gt; <a href="index.html">AFS/DDC/OLE: Function servers</a> &gt; AFS Doubt</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">luis melo</div><div class="date">8th May 2004, 00:50</div></div><div class="posttext">When I´m running the command &quot;stppai.insert&quot; the error message is displayed ==&gt; msg.error.o = &quot;Command cancelled&quot;, but the process is finished correctly. What is the problem? Help me, i need a aswer for this.<br />
<br />
Thank´s for all.<br />
<br />
See below the program script ticfs0202m000, when a production is posted in warehouse:<br />
 <br />
        msg.error.o = &quot;&quot;<br />
        stpapi.put.field(&quot;tisfc0202m000&quot;,&quot;tisfc001.pdno&quot;,str$(ordem))<br />
        ret.o = stpapi.find(&quot;tisfc0202m000&quot;)<br />
        stpapi.get.field(&quot;tisfc0202m000&quot;,&quot;tisfc001.mitm&quot;,cod.item)<br />
        if ret.o = 1 then<br />
                stpapi.put.field(&quot;tisfc0202m000&quot;,&quot;qdlv.frm&quot;,str$(aponta))<br />
                stpapi.enum.answer(&quot;tisfc0202m000&quot;,&quot;tisfc02029&quot;,tcyesno.yes)<br />
                stpapi.handle.subproc(&quot;tisfc0202m000&quot;,&quot;tdilc4113s000&quot;,&quot;add&quot;)<br />
                stpapi.continue.process(&quot;tisfc0202m000&quot;,msg.error.o)<br />
                if msg.error.o &lt;&gt; &quot;&quot; then<br />
                        erro.subsession.o = true<br />
                        erro.msg.o = msg.error.o<br />
                        stpapi.recover(&quot;tisfc0202m000&quot;,msg.error.o)<br />
                else<br />
                        stpapi.insert(&quot;tdilc4113s000&quot;,1,msg.error.o)<br />
                        if msg.error.o &lt;&gt; &quot;&quot; then<br />
                                erro.subsession.o = true<br />
                                erro.msg.o = msg.error.o<br />
                                stpapi.recover(&quot;tdilc4213s000&quot;,msg.error.o)<br />
<br />
                                stpapi.end.session(&quot;tdilc4113s000&quot;)<br />
                        else<br />
                                stpapi.end.session(&quot;tdilc4113s000&quot;)<br />
                        endif<br />
                endif<br />
        endif<br />
        stpapi.end.session(&quot;tisfc0202m000&quot;)</div></div><hr />


<div class="post"><div class="posttop"><div class="username">mark_h</div><div class="date">8th May 2004, 17:02</div></div><div class="posttext">If the session works I usually do not worry about the errors like Process Gone or Command Cancelled.  I am not sure I have run into the Command Cancelled error, but I do know I have run into the process gone error.  I just ignore them and code around them.  Since we do not own source I have never looked really hard at what causes these type errors, but I think it is the execute(end.program) or something like that.  I think there is another post or two in this forum about that.  Here is one such post (http://www.baanboard.com/baanboard/showthread.php?s=&amp;threadid=6910&amp;highlight=process+gone) .<br />
<br />
<br />
Mark</div></div><hr />


<div class="post"><div class="posttop"><div class="username">mark_h</div><div class="date">12th May 2004, 16:27</div></div><div class="posttext">I got this response in a report this thread message and I think luis just meant to do a reply.<br />
<br />
Thanks Mark for your answer.<br />
<br />
After to search in the site, I obtained a manual that describes this type of error, where in mine case the &quot;Command cancelled&quot; was occurring for existing an instruction of choice.again without no associated message in the script called.<br />
<br />
Ex: <br />
field.ccmcs004.codf.o:<br />
check.input:<br />
        if ccmcs004.codf.o &gt; 10  then<br />
                    set.input.error(&quot;&quot;)       * return for call AFS (error.o = &quot;Input cancelled on field Codigoö)      <br />
        endif<br />
<br />
<br />
choice.update.db:<br />
before.choice:<br />
        if api.mode then                                <br />
                        choice.again()        * return for call AFS ( error.o = &quot;Command cancelled&quot;)<br />
        endif</div></div><hr />


<div class="post"><div class="posttop"><div class="username">baan2tm0</div><div class="date">1st February 2005, 16:09</div></div><div class="posttext">:cool: I've noticed that sometimes a &quot;Command Cancelled&quot; can be caused when a line (for e.g. sales order line) has been locked. Maybe the &quot;Remove Application Lock&quot;(ttstpdellocks) has to be run and all the application locks has to be deleted.</div></div><hr />



</div>
</body>
</html>