<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="Process is gone in Release outbound, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] Process is gone in Release outbound AFS/DDC/OLE: Function servers" />
	
	<title>Process is gone in Release outbound [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="index.html">Newbaanboard</a> &gt; <a href="index.html">Baan SIGs</a> &gt; <a href="index.html">AFS/DDC/OLE: Function servers</a> &gt; Process is gone in Release outbound</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">Ilansu</div><div class="date">24th November 2002, 10:55</div></div><div class="posttext">Hi.<br />
<br />
I'm trying to use AFS with the Maintain outbound data.<br />
I have a problem with the Release outbound report.<br />
<br />
I have source codes .<br />
<br />
I made some changes to the tdilc4202 script, so if the api.mode is true it should ignore the open/close of the reports.<br />
<br />
This is my AFS code:<br />
<br />
Get.orno.pono.to.update()<br />
<br />
stpapi.put.field(&quot;tdilc4101m000&quot;,&quot;runnumber&quot;,run.number)<br />
stpapi.put.field(&quot;tdilc4101m000&quot;,&quot;k.o.order&quot;,&quot;7&quot;)<br />
stpapi.put.field(&quot;tdilc4101m000&quot;,&quot;ordernr&quot;,str$( orno))<br />
stpapi.handle.subproc(&quot;tdilc4101m000&quot;,&quot;tdilc4102s000&quot;,&quot;add&quot;)<br />
stpapi.continue.process( &quot;tdilc4101m000&quot;, e.mess )<br />
stpapi.put.field(&quot;tdilc4102s000&quot;,&quot;tdilc401.koor&quot;,&quot;7&quot;)<br />
stpapi.put.field(&quot;tdilc4102s000&quot;,&quot;tdilc401.orno&quot;,str$(orno))<br />
stpapi.put.field(&quot;tdilc4102s000&quot;,&quot;tdilc401.pono&quot;,str$(pono))<br />
stpapi.put.field(&quot;tdilc4102s000&quot;,&quot;tdilc401.qstr&quot;,str$(quan))<br />
stpapi.insert( &quot;tdilc4102s000&quot;, 1, e.mess )<br />
stpapi.handle.subproc(&quot;tdilc4101m000&quot;,&quot;tdilc4102s000&quot;,&quot;kill&quot;)<br />
stpapi.end.session(&quot;tdilc4102s000&quot;)<br />
<br />
stpapi.handle.subproc(&quot;tdilc4101m000&quot;,&quot;tdilc4202s000&quot;,&quot;add&quot;)<br />
stpapi.zoom.option( &quot;tdilc4101m000&quot;, 1, &quot;tdilc4202s000&quot;, e.mess )<br />
<br />
if isspace(e.mess) then<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;runnumber.f&quot;,run.number)<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;runnumber.t&quot;,run.number)<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;koor.f&quot;,&quot;7&quot;)<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;koor.t&quot;,&quot;7&quot;)	<br />
      stpapi.put.field(&quot;tdilc4202s0000&quot;,&quot;orno.f&quot;,str$(orno))<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;orno.t&quot;,str$(orno))<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;prdf.f&quot;,str$(date.num()))<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;ddta.f&quot;,str.ddta.f)<br />
      stpapi.put.field(&quot;tdilc4202s000&quot;,&quot;ddta.t&quot;,str.ddta.t)<br />
<br />
      stpapi.continue.process( &quot;tdilc4202s000&quot;, e.mess )<br />
endif<br />
<br />
stpapi.handle.subproc(&quot;tdilc4101m000&quot;,&quot;tdilc4202s000&quot;,&quot;kill&quot;)<br />
stpapi.end.session(&quot;tdilc4202s000&quot;)<br />
stpapi.end.session(&quot;tdilc4101m000&quot;)<br />
<br />
	if isspace(e.mess) then<br />
		field.update<br />
		db.update(table,db.retry)<br />
		commit.transaction()<br />
	endif<br />
<br />
<br />
The problem is at the last continue.process.<br />
The outbound is released  but e.mess=&quot;Process in gone&quot; and my field.update is canceled.<br />
<br />
The changes i made to tdilc4202 are like this:<br />
<br />
|if not open.report(1,&quot;&quot;,1,language$,1) then		<br />
 if not api.mode and not open.report(1,&quot;&quot;,1,language$,1) then	<br />
if a_close.report  and not api.mode  then		<br />
        if not COUNTER and not BACKFLUSH then<br />
		close.reports(2)<br />
	else<br />
		close.reports(0)<br />
        endif<br />
endif<br />
after.choice:<br />
	if (background or job.process) and a_end.prog then<br />
		execute(end.program)<br />
	endif<br />
<br />
choice.end.program:<br />
before.choice:<br />
	itfglddll4010.invoke.background.after.session() <br />
<br />
The error message comes from: <br />
 itfglddll4010.invoke.background.after.session()  <br />
<br />
Thanks <br />
Ilan S</div></div><hr />


<div class="post"><div class="posttop"><div class="username">mark_h</div><div class="date">24th November 2002, 23:16</div></div><div class="posttext">I have had function server problems when programs executed the end.program event.  Is everything in the itfglddll4010.invoke.background.after.session() subroutine getting executed correctly?  If so then why not do this?<br />
<br />
<br />
     if isspace(e.mess) or strip$(e.mess)=&quot;Process is gone&quot; then<br />
           field.update<br />
           db.update(table,db.retry)<br />
           commit.transaction()<br />
     endif<br />
<br />
<br />
I have this in a couple of my function servers.  In some I also check for Command Cancelled - if I recall correctly.  In both cases I checked to make sure everything worked okay.  So as long as everything worked okay then I see do not see a reason to skip your update statements.<br />
<br />
Hope this helps.<br />
<br />
Mark</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Ilansu</div><div class="date">25th November 2002, 09:48</div></div><div class="posttext">Mark Hi.<br />
<br />
Surely I could ignore this specific message but I was looking for the reason to the problem.<br />
<br />
The command cancelled comes from the &quot; choice.again() &quot; function.<br />
<br />
Thanks <br />
Ilan S</div></div><hr />


<div class="post"><div class="posttop"><div class="username">mark_h</div><div class="date">25th November 2002, 14:15</div></div><div class="posttext">Since I do not own code I have never been able to trace it down to a specific section.  I did notice that I got it from the sessions that did an execute(end.program) command.  The only thing I can figure is that when the program ends and returns control to the function server the the program that you called is already gone.  And since you are returning to the stpapi command you get the error. And in some cases a stpapi.end.session will hang becuase the program is already gone.  Is this making sense?  I really think it is just the fact that the stpapi commands expect the session to still be there in the background and the end.program section stops this.<br />
<br />
Mark</div></div><hr />


<div class="post"><div class="posttop"><div class="username">Ilansu</div><div class="date">25th November 2002, 15:19</div></div><div class="posttext">Thanks          :D :D :D <br />
<br />
Ilan S</div></div><hr />



</div>
</body>
</html>