<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="keywords" content="Error when using DAL to insert a date field, baan,baanerp,erp,forum,discussion,bulletin board" />
	<meta name="description" content="[Archive] Error when using DAL to insert a date field Tools Development" />
	
	<title>Error when using DAL to insert a date field [Archive]  - Baanboard.com</title>
	<link rel="stylesheet" type="text/css" href="../styles.css" />
</head>
<body>
<div class="pagebody">
<div id="navbar"><a href="../index.html">Newbaanboard</a> &gt; <a href="../index.html">Baan Quick Support: Functional &amp; Technical</a> &gt; <a href="../index.html">Tools Development</a> &gt; Error when using DAL to insert a date field</div>
<hr />
<div class="pda"></div>

<hr />

<div class="post"><div class="posttop"><div class="username">tmannais</div><div class="date">12th December 2019, 06:36</div></div><div class="posttext">I am working on a customized session where I am trying to insert a Sales Order Line into a Sales Order Header using DAL.<br />
<br />
if dal.new.object(&quot;tdsls401&quot;) &lt;&gt; 0 then<br />
	dal.get.error.message(error.msg)<br />
	return(error.msg)<br />
endif<br />
dal.set.field(&quot;tdsls401.orno&quot;, i.sales.order)<br />
dal.set.field(&quot;tdsls401.ofbp&quot;, i.stbp)<br />
dal.set.field(&quot;tdsls401.odat&quot;, utc.num()) |* The error occurs when I add this line<br />
dal.set.field(&quot;tdsls401.pono&quot;, i.position)<br />
dal.set.field(&quot;tdsls401.item&quot;, i.item)<br />
dal.set.field(&quot;tdsls401.qoor&quot;, i.qty)<br />
dal.set.field(&quot;tdsls401.pric&quot;, i.price)<br />
dal.set.field(&quot;tdsls401.ldam&quot;, i.discount)<br />
if dal.save.object(&quot;tdsls401&quot;) &lt;&gt; 0 then<br />
	dal.get.error.message(error.msg)<br />
	return(error.msg)<br />
endif<br />
<br />
See the error in attached image.<br />
The error happens when it reaches &quot;dal.set.field(&quot;tdsls401.odat&quot;, utc.num())&quot;.<br />
If I don't add the line, it will display another error Release Date is required but it is also a date field, which I also cannot solve that error even when I send a date.<br />
<br />
Any help is appreciated.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">martin.f</div><div class="date">12th December 2019, 17:01</div></div><div class="posttext">Try to initialize the date outside:<br />
<br />
domain tcdate today<br />
today = utc.date()<br />
<br />
<br />
dal.set.field(&quot;tdsls401.odat&quot;, today)<br />
<br />
Regards<br />
Martin</div></div><hr />


<div class="post"><div class="posttop"><div class="username">tmannais</div><div class="date">13th December 2019, 03:44</div></div><div class="posttext">Try to initialize the date outside:<br />
<br />
domain tcdate today<br />
today = utc.date()<br />
<br />
<br />
dal.set.field(&quot;tdsls401.odat&quot;, today)<br />
<br />
Regards<br />
Martin<br />
<br />
I tried it but it does not work.<br />
The error is still the same.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">srkndnsn</div><div class="date">13th December 2019, 07:48</div></div><div class="posttext">I am working on a customized session where I am trying to insert a Sales Order Line into a Sales Order Header using DAL.<br />
<br />
if dal.new.object(&quot;tdsls401&quot;) &lt;&gt; 0 then<br />
	dal.get.error.message(error.msg)<br />
	return(error.msg)<br />
endif<br />
dal.set.field(&quot;tdsls401.orno&quot;, i.sales.order)<br />
dal.set.field(&quot;tdsls401.ofbp&quot;, i.stbp)<br />
dal.set.field(&quot;tdsls401.odat&quot;, utc.num()) |* The error occurs when I add this line<br />
dal.set.field(&quot;tdsls401.pono&quot;, i.position)<br />
dal.set.field(&quot;tdsls401.item&quot;, i.item)<br />
dal.set.field(&quot;tdsls401.qoor&quot;, i.qty)<br />
dal.set.field(&quot;tdsls401.pric&quot;, i.price)<br />
dal.set.field(&quot;tdsls401.ldam&quot;, i.discount)<br />
if dal.save.object(&quot;tdsls401&quot;) &lt;&gt; 0 then<br />
	dal.get.error.message(error.msg)<br />
	return(error.msg)<br />
endif<br />
<br />
See the error in attached image.<br />
The error happens when it reaches &quot;dal.set.field(&quot;tdsls401.odat&quot;, utc.num())&quot;.<br />
If I don't add the line, it will display another error Release Date is required but it is also a date field, which I also cannot solve that error even when I send a date.<br />
<br />
Any help is appreciated.<br />
<br />
dal.set.field(&quot;tdsls401.odat&quot;, utc.num())  this should be worked. We are using everyday in Infor LN 10.4 . Maybe in the 10.5; the domain has been changed in the tdsls401. Can you check this?<br />
<br />
Best,<br />
Serkan</div></div><hr />


<div class="post"><div class="posttop"><div class="username">tmannais</div><div class="date">13th December 2019, 08:32</div></div><div class="posttext">dal.set.field(&quot;tdsls401.odat&quot;, utc.num())  this should be worked. We are using everyday in Infor LN 10.4 . Maybe in the 10.5; the domain has been changed in the tdsls401. Can you check this?<br />
<br />
Best,<br />
Serkan<br />
<br />
The domain is tcdate.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">tmannais</div><div class="date">13th February 2020, 12:00</div></div><div class="posttext">I just solved the problem.<br />
<br />
It is accidentally caused by another variable in my script named &quot;status&quot; as extern variable.<br />
<br />
This name is used in some dll that dal apparently calls within itself. So, the variable name collides with standard dll hence the error.<br />
<br />
Changing the variable name from &quot;status&quot; to something else does solve the issue.</div></div><hr />


<div class="post"><div class="posttop"><div class="username">srkndnsn</div><div class="date">13th February 2020, 13:30</div></div><div class="posttext">I just solved the problem.<br />
<br />
It is accidentally caused by another variable in my script named &quot;status&quot; as extern variable.<br />
<br />
This name is used in some dll that dal apparently calls within itself. So, the variable name collides with standard dll hence the error.<br />
<br />
Changing the variable name from &quot;status&quot; to something else does solve the issue.<br />
<br />
I am glad you have solved it. But that one is tricky.<br />
<br />
We should never prefer the variable names which can be used in dll :)</div></div><hr />



</div>
</body>
</html>